POST http://localhost:3000/api/services
Content-Type: application/json

{
    "name": "algum serviço",
    "description": "algum descrição",
    "price": 1400,
    "image": "https://www.shutterstock.com/pt/featured-collections/esportes-para-pessoas-com-312012655"
}

###

GET http://localhost:3000/api/services